/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "ALU_Control.v:1" *)
module ALU_Control(\funct_i[0] , \funct_i[1] , \funct_i[2] , \funct_i[3] , \funct_i[4] , \funct_i[5] , \funct_i[6] , \funct_i[7] , \funct_i[8] , \funct_i[9] , \ALUOp_i[0] , \ALUOp_i[1] , \ALUCtrl_o[0] , \ALUCtrl_o[1] , \ALUCtrl_o[2] );
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  (* src = "ALU_Control.v:9" *)
  output \ALUCtrl_o[0] ;
  (* src = "ALU_Control.v:9" *)
  output \ALUCtrl_o[1] ;
  (* src = "ALU_Control.v:9" *)
  output \ALUCtrl_o[2] ;
  (* src = "ALU_Control.v:8" *)
  input \ALUOp_i[0] ;
  (* src = "ALU_Control.v:8" *)
  input \ALUOp_i[1] ;
  (* src = "ALU_Control.v:7" *)
  input \funct_i[0] ;
  (* src = "ALU_Control.v:7" *)
  input \funct_i[1] ;
  (* src = "ALU_Control.v:7" *)
  input \funct_i[2] ;
  (* src = "ALU_Control.v:7" *)
  input \funct_i[3] ;
  (* src = "ALU_Control.v:7" *)
  input \funct_i[4] ;
  (* src = "ALU_Control.v:7" *)
  input \funct_i[5] ;
  (* src = "ALU_Control.v:7" *)
  input \funct_i[6] ;
  (* src = "ALU_Control.v:7" *)
  input \funct_i[7] ;
  (* src = "ALU_Control.v:7" *)
  input \funct_i[8] ;
  (* src = "ALU_Control.v:7" *)
  input \funct_i[9] ;
  NOT _29_ (
    .A(\ALUOp_i[1] ),
    .Y(_00_)
  );
  NOT _30_ (
    .A(\funct_i[3] ),
    .Y(_01_)
  );
  NAND _31_ (
    .A(\ALUOp_i[0] ),
    .B(_00_),
    .Y(_02_)
  );
  NOR _32_ (
    .A(\funct_i[5] ),
    .B(\funct_i[4] ),
    .Y(_03_)
  );
  NOR _33_ (
    .A(\funct_i[7] ),
    .B(\funct_i[6] ),
    .Y(_04_)
  );
  NAND _34_ (
    .A(_03_),
    .B(_04_),
    .Y(_05_)
  );
  NOR _35_ (
    .A(\funct_i[0] ),
    .B(_05_),
    .Y(_06_)
  );
  NOR _36_ (
    .A(\funct_i[1] ),
    .B(\funct_i[2] ),
    .Y(_07_)
  );
  AND _37_ (
    .A(_06_),
    .B(_07_),
    .Y(_08_)
  );
  NOR _38_ (
    .A(\funct_i[9] ),
    .B(\funct_i[8] ),
    .Y(_09_)
  );
  AND _39_ (
    .A(\funct_i[3] ),
    .B(_09_),
    .Y(_10_)
  );
  NAND _40_ (
    .A(_08_),
    .B(_10_),
    .Y(_11_)
  );
  AND _41_ (
    .A(\funct_i[1] ),
    .B(\funct_i[2] ),
    .Y(_12_)
  );
  AND _42_ (
    .A(_01_),
    .B(_09_),
    .Y(_13_)
  );
  AND _43_ (
    .A(_12_),
    .B(_13_),
    .Y(_14_)
  );
  NAND _44_ (
    .A(_06_),
    .B(_14_),
    .Y(_15_)
  );
  AND _45_ (
    .A(_11_),
    .B(_15_),
    .Y(_16_)
  );
  NAND _46_ (
    .A(_11_),
    .B(_15_),
    .Y(_17_)
  );
  NOR _47_ (
    .A(\funct_i[3] ),
    .B(\funct_i[9] ),
    .Y(_18_)
  );
  AND _48_ (
    .A(\funct_i[8] ),
    .B(_18_),
    .Y(_19_)
  );
  NAND _49_ (
    .A(_08_),
    .B(_19_),
    .Y(_20_)
  );
  NAND _50_ (
    .A(_16_),
    .B(_20_),
    .Y(_21_)
  );
  NOR _51_ (
    .A(\ALUOp_i[0] ),
    .B(_00_),
    .Y(_22_)
  );
  NAND _52_ (
    .A(\funct_i[0] ),
    .B(_14_),
    .Y(_23_)
  );
  OR _53_ (
    .A(_05_),
    .B(_23_),
    .Y(_24_)
  );
  NAND _54_ (
    .A(_21_),
    .B(_22_),
    .Y(_25_)
  );
  AND _55_ (
    .A(_02_),
    .B(_25_),
    .Y(\ALUCtrl_o[0] )
  );
  AND _56_ (
    .A(_11_),
    .B(_24_),
    .Y(_26_)
  );
  NAND _57_ (
    .A(_20_),
    .B(_26_),
    .Y(_27_)
  );
  NAND _58_ (
    .A(_22_),
    .B(_27_),
    .Y(_28_)
  );
  NAND _59_ (
    .A(_02_),
    .B(_28_),
    .Y(\ALUCtrl_o[1] )
  );
  AND _60_ (
    .A(_17_),
    .B(_22_),
    .Y(\ALUCtrl_o[2] )
  );
endmodule
