/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "PC.v:22" *)
module PC(clk_i, se, si start_i, \pc_i[0] , \pc_i[1] , \pc_i[2] , \pc_i[3] , \pc_i[4] , \pc_i[5] , \pc_i[6] , \pc_i[7] , \pc_i[8] , \pc_i[9] , \pc_i[10] , \pc_i[11] , \pc_i[12] , \pc_i[13] , \pc_i[14] , \pc_i[15] , \pc_i[16] , \pc_i[17] , \pc_i[18] , \pc_i[19] , \pc_i[20] , \pc_i[21] , \pc_i[22] , \pc_i[23] , \pc_i[24] , \pc_i[25] , \pc_i[26] , \pc_i[27] , \pc_i[28] , \pc_i[29] , \pc_i[30] , \pc_i[31] , hazardpc_i, \pc_o[0] , \pc_o[1] , \pc_o[2] , \pc_o[3] , \pc_o[4] , \pc_o[5] , \pc_o[6] , \pc_o[7] , \pc_o[8] , \pc_o[9] , \pc_o[10] , \pc_o[11] , \pc_o[12] , \pc_o[13] , \pc_o[14] , \pc_o[15] , \pc_o[16] , \pc_o[17] , \pc_o[18] , \pc_o[19] , \pc_o[20] , \pc_o[21] , \pc_o[22] , \pc_o[23] , \pc_o[24] , \pc_o[25] , \pc_o[26] , \pc_o[27] , \pc_o[28] , \pc_o[29] , \pc_o[30] , \pc_o[31] );
  (* src = "PC.v:46" *)
  wire _000_;
  (* src = "PC.v:46" *)
  wire _001_;
  (* src = "PC.v:46" *)
  wire _002_;
  (* src = "PC.v:46" *)
  wire _003_;
  (* src = "PC.v:46" *)
  wire _004_;
  (* src = "PC.v:46" *)
  wire _005_;
  (* src = "PC.v:46" *)
  wire _006_;
  (* src = "PC.v:46" *)
  wire _007_;
  (* src = "PC.v:46" *)
  wire _008_;
  (* src = "PC.v:46" *)
  wire _009_;
  (* src = "PC.v:46" *)
  wire _010_;
  (* src = "PC.v:46" *)
  wire _011_;
  (* src = "PC.v:46" *)
  wire _012_;
  (* src = "PC.v:46" *)
  wire _013_;
  (* src = "PC.v:46" *)
  wire _014_;
  (* src = "PC.v:46" *)
  wire _015_;
  (* src = "PC.v:46" *)
  wire _016_;
  (* src = "PC.v:46" *)
  wire _017_;
  (* src = "PC.v:46" *)
  wire _018_;
  (* src = "PC.v:46" *)
  wire _019_;
  (* src = "PC.v:46" *)
  wire _020_;
  (* src = "PC.v:46" *)
  wire _021_;
  (* src = "PC.v:46" *)
  wire _022_;
  (* src = "PC.v:46" *)
  wire _023_;
  (* src = "PC.v:46" *)
  wire _024_;
  (* src = "PC.v:46" *)
  wire _025_;
  (* src = "PC.v:46" *)
  wire _026_;
  (* src = "PC.v:46" *)
  wire _027_;
  (* src = "PC.v:46" *)
  wire _028_;
  (* src = "PC.v:46" *)
  wire _029_;
  (* src = "PC.v:46" *)
  wire _030_;
  (* src = "PC.v:46" *)
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  (* src = "PC.v:32" *)
  input clk_i;
  (* src = "PC.v:39" *)
  wire flag;
  (* src = "PC.v:39" *)
  wire flag_next;
  (* src = "PC.v:33" *)
  input hazardpc_i;
  (* src = "PC.v:34" *)
  input \pc_i[0] ;
  (* src = "PC.v:34" *)
  input \pc_i[10] ;
  (* src = "PC.v:34" *)
  input \pc_i[11] ;
  (* src = "PC.v:34" *)
  input \pc_i[12] ;
  (* src = "PC.v:34" *)
  input \pc_i[13] ;
  (* src = "PC.v:34" *)
  input \pc_i[14] ;
  (* src = "PC.v:34" *)
  input \pc_i[15] ;
  (* src = "PC.v:34" *)
  input \pc_i[16] ;
  (* src = "PC.v:34" *)
  input \pc_i[17] ;
  (* src = "PC.v:34" *)
  input \pc_i[18] ;
  (* src = "PC.v:34" *)
  input \pc_i[19] ;
  (* src = "PC.v:34" *)
  input \pc_i[1] ;
  (* src = "PC.v:34" *)
  input \pc_i[20] ;
  (* src = "PC.v:34" *)
  input \pc_i[21] ;
  (* src = "PC.v:34" *)
  input \pc_i[22] ;
  (* src = "PC.v:34" *)
  input \pc_i[23] ;
  (* src = "PC.v:34" *)
  input \pc_i[24] ;
  (* src = "PC.v:34" *)
  input \pc_i[25] ;
  (* src = "PC.v:34" *)
  input \pc_i[26] ;
  (* src = "PC.v:34" *)
  input \pc_i[27] ;
  (* src = "PC.v:34" *)
  input \pc_i[28] ;
  (* src = "PC.v:34" *)
  input \pc_i[29] ;
  (* src = "PC.v:34" *)
  input \pc_i[2] ;
  (* src = "PC.v:34" *)
  input \pc_i[30] ;
  (* src = "PC.v:34" *)
  input \pc_i[31] ;
  (* src = "PC.v:34" *)
  input \pc_i[3] ;
  (* src = "PC.v:34" *)
  input \pc_i[4] ;
  (* src = "PC.v:34" *)
  input \pc_i[5] ;
  (* src = "PC.v:34" *)
  input \pc_i[6] ;
  (* src = "PC.v:34" *)
  input \pc_i[7] ;
  (* src = "PC.v:34" *)
  input \pc_i[8] ;
  (* src = "PC.v:34" *)
  input \pc_i[9] ;
  (* src = "PC.v:35" *)
  output \pc_o[0] ;
  (* src = "PC.v:35" *)
  output \pc_o[10] ;
  (* src = "PC.v:35" *)
  output \pc_o[11] ;
  (* src = "PC.v:35" *)
  output \pc_o[12] ;
  (* src = "PC.v:35" *)
  output \pc_o[13] ;
  (* src = "PC.v:35" *)
  output \pc_o[14] ;
  (* src = "PC.v:35" *)
  output \pc_o[15] ;
  (* src = "PC.v:35" *)
  output \pc_o[16] ;
  (* src = "PC.v:35" *)
  output \pc_o[17] ;
  (* src = "PC.v:35" *)
  output \pc_o[18] ;
  (* src = "PC.v:35" *)
  output \pc_o[19] ;
  (* src = "PC.v:35" *)
  output \pc_o[1] ;
  (* src = "PC.v:35" *)
  output \pc_o[20] ;
  (* src = "PC.v:35" *)
  output \pc_o[21] ;
  (* src = "PC.v:35" *)
  output \pc_o[22] ;
  (* src = "PC.v:35" *)
  output \pc_o[23] ;
  (* src = "PC.v:35" *)
  output \pc_o[24] ;
  (* src = "PC.v:35" *)
  output \pc_o[25] ;
  (* src = "PC.v:35" *)
  output \pc_o[26] ;
  (* src = "PC.v:35" *)
  output \pc_o[27] ;
  (* src = "PC.v:35" *)
  output \pc_o[28] ;
  (* src = "PC.v:35" *)
  output \pc_o[29] ;
  (* src = "PC.v:35" *)
  output \pc_o[2] ;
  (* src = "PC.v:35" *)
  output \pc_o[30] ;
  (* src = "PC.v:35" *)
  output \pc_o[31] ;
  (* src = "PC.v:35" *)
  output \pc_o[3] ;
  (* src = "PC.v:35" *)
  output \pc_o[4] ;
  (* src = "PC.v:35" *)
  output \pc_o[5] ;
  (* src = "PC.v:35" *)
  output \pc_o[6] ;
  (* src = "PC.v:35" *)
  output \pc_o[7] ;
  (* src = "PC.v:35" *)
  output \pc_o[8] ;
  (* src = "PC.v:35" *)
  output \pc_o[9] ;
  (* src = "PC.v:33" *)
  input start_i;
  input se;
  input si;
  
  NOT _197_ (
    .A(start_i),
    .Y(_064_)
  );
  NOT _198_ (
    .A(flag),
    .Y(_065_)
  );
  NOT _199_ (
    .A(\pc_i[2] ),
    .Y(_066_)
  );
  NOT _200_ (
    .A(hazardpc_i),
    .Y(_067_)
  );
  AND _201_ (
    .A(start_i),
    .B(_067_),
    .Y(_068_)
  );
  NAND _202_ (
    .A(start_i),
    .B(_067_),
    .Y(_069_)
  );
  NAND _203_ (
    .A(\pc_i[0] ),
    .B(_065_),
    .Y(_070_)
  );
  NAND _204_ (
    .A(_068_),
    .B(_070_),
    .Y(_071_)
  );
  OR _205_ (
    .A(\pc_o[0] ),
    .B(_068_),
    .Y(_072_)
  );
  AND _206_ (
    .A(_071_),
    .B(_072_),
    .Y(_000_)
  );
  NAND _207_ (
    .A(_065_),
    .B(\pc_i[1] ),
    .Y(_073_)
  );
  NAND _208_ (
    .A(_068_),
    .B(_073_),
    .Y(_074_)
  );
  OR _209_ (
    .A(\pc_o[1] ),
    .B(_068_),
    .Y(_075_)
  );
  AND _210_ (
    .A(_074_),
    .B(_075_),
    .Y(_011_)
  );
  NAND _211_ (
    .A(_065_),
    .B(\pc_i[2] ),
    .Y(_076_)
  );
  NAND _212_ (
    .A(_068_),
    .B(_076_),
    .Y(_077_)
  );
  OR _213_ (
    .A(\pc_o[2] ),
    .B(_068_),
    .Y(_078_)
  );
  AND _214_ (
    .A(_077_),
    .B(_078_),
    .Y(_022_)
  );
  OR _215_ (
    .A(flag),
    .B(\pc_i[3] ),
    .Y(_079_)
  );
  NAND _216_ (
    .A(_068_),
    .B(_079_),
    .Y(_080_)
  );
  NAND _217_ (
    .A(\pc_o[3] ),
    .B(_069_),
    .Y(_081_)
  );
  NAND _218_ (
    .A(_080_),
    .B(_081_),
    .Y(_025_)
  );
  OR _219_ (
    .A(flag),
    .B(\pc_i[4] ),
    .Y(_082_)
  );
  NAND _220_ (
    .A(_068_),
    .B(_082_),
    .Y(_083_)
  );
  NAND _221_ (
    .A(\pc_o[4] ),
    .B(_069_),
    .Y(_084_)
  );
  NAND _222_ (
    .A(_083_),
    .B(_084_),
    .Y(_026_)
  );
  OR _223_ (
    .A(flag),
    .B(\pc_i[5] ),
    .Y(_085_)
  );
  NAND _224_ (
    .A(_068_),
    .B(_085_),
    .Y(_086_)
  );
  NAND _225_ (
    .A(\pc_o[5] ),
    .B(_069_),
    .Y(_087_)
  );
  NAND _226_ (
    .A(_086_),
    .B(_087_),
    .Y(_027_)
  );
  OR _227_ (
    .A(flag),
    .B(\pc_i[6] ),
    .Y(_088_)
  );
  NAND _228_ (
    .A(_068_),
    .B(_088_),
    .Y(_089_)
  );
  NAND _229_ (
    .A(\pc_o[6] ),
    .B(_069_),
    .Y(_090_)
  );
  NAND _230_ (
    .A(_089_),
    .B(_090_),
    .Y(_028_)
  );
  OR _231_ (
    .A(flag),
    .B(\pc_i[7] ),
    .Y(_091_)
  );
  NAND _232_ (
    .A(_068_),
    .B(_091_),
    .Y(_092_)
  );
  NAND _233_ (
    .A(\pc_o[7] ),
    .B(_069_),
    .Y(_093_)
  );
  NAND _234_ (
    .A(_092_),
    .B(_093_),
    .Y(_029_)
  );
  NAND _235_ (
    .A(_065_),
    .B(\pc_i[8] ),
    .Y(_094_)
  );
  NAND _236_ (
    .A(_068_),
    .B(_094_),
    .Y(_095_)
  );
  OR _237_ (
    .A(\pc_o[8] ),
    .B(_068_),
    .Y(_096_)
  );
  AND _238_ (
    .A(_095_),
    .B(_096_),
    .Y(_030_)
  );
  NAND _239_ (
    .A(_065_),
    .B(\pc_i[9] ),
    .Y(_097_)
  );
  NAND _240_ (
    .A(_068_),
    .B(_097_),
    .Y(_098_)
  );
  OR _241_ (
    .A(\pc_o[9] ),
    .B(_068_),
    .Y(_099_)
  );
  AND _242_ (
    .A(_098_),
    .B(_099_),
    .Y(_031_)
  );
  NAND _243_ (
    .A(_065_),
    .B(\pc_i[10] ),
    .Y(_100_)
  );
  NAND _244_ (
    .A(_068_),
    .B(_100_),
    .Y(_101_)
  );
  OR _245_ (
    .A(\pc_o[10] ),
    .B(_068_),
    .Y(_102_)
  );
  AND _246_ (
    .A(_101_),
    .B(_102_),
    .Y(_001_)
  );
  NAND _247_ (
    .A(_065_),
    .B(\pc_i[11] ),
    .Y(_103_)
  );
  NAND _248_ (
    .A(_068_),
    .B(_103_),
    .Y(_104_)
  );
  OR _249_ (
    .A(\pc_o[11] ),
    .B(_068_),
    .Y(_105_)
  );
  AND _250_ (
    .A(_104_),
    .B(_105_),
    .Y(_002_)
  );
  NAND _251_ (
    .A(_065_),
    .B(\pc_i[12] ),
    .Y(_106_)
  );
  NAND _252_ (
    .A(_068_),
    .B(_106_),
    .Y(_107_)
  );
  OR _253_ (
    .A(\pc_o[12] ),
    .B(_068_),
    .Y(_108_)
  );
  AND _254_ (
    .A(_107_),
    .B(_108_),
    .Y(_003_)
  );
  NAND _255_ (
    .A(_065_),
    .B(\pc_i[13] ),
    .Y(_109_)
  );
  NAND _256_ (
    .A(_068_),
    .B(_109_),
    .Y(_110_)
  );
  OR _257_ (
    .A(\pc_o[13] ),
    .B(_068_),
    .Y(_111_)
  );
  AND _258_ (
    .A(_110_),
    .B(_111_),
    .Y(_004_)
  );
  NAND _259_ (
    .A(_065_),
    .B(\pc_i[14] ),
    .Y(_112_)
  );
  NAND _260_ (
    .A(_068_),
    .B(_112_),
    .Y(_113_)
  );
  OR _261_ (
    .A(\pc_o[14] ),
    .B(_068_),
    .Y(_114_)
  );
  AND _262_ (
    .A(_113_),
    .B(_114_),
    .Y(_005_)
  );
  NAND _263_ (
    .A(_065_),
    .B(\pc_i[15] ),
    .Y(_115_)
  );
  NAND _264_ (
    .A(_068_),
    .B(_115_),
    .Y(_116_)
  );
  OR _265_ (
    .A(\pc_o[15] ),
    .B(_068_),
    .Y(_117_)
  );
  AND _266_ (
    .A(_116_),
    .B(_117_),
    .Y(_006_)
  );
  NAND _267_ (
    .A(_065_),
    .B(\pc_i[16] ),
    .Y(_118_)
  );
  NAND _268_ (
    .A(_068_),
    .B(_118_),
    .Y(_119_)
  );
  OR _269_ (
    .A(\pc_o[16] ),
    .B(_068_),
    .Y(_120_)
  );
  AND _270_ (
    .A(_119_),
    .B(_120_),
    .Y(_007_)
  );
  NAND _271_ (
    .A(_065_),
    .B(\pc_i[17] ),
    .Y(_121_)
  );
  NAND _272_ (
    .A(_068_),
    .B(_121_),
    .Y(_122_)
  );
  OR _273_ (
    .A(\pc_o[17] ),
    .B(_068_),
    .Y(_123_)
  );
  AND _274_ (
    .A(_122_),
    .B(_123_),
    .Y(_008_)
  );
  NAND _275_ (
    .A(_065_),
    .B(\pc_i[18] ),
    .Y(_124_)
  );
  NAND _276_ (
    .A(_068_),
    .B(_124_),
    .Y(_125_)
  );
  OR _277_ (
    .A(\pc_o[18] ),
    .B(_068_),
    .Y(_126_)
  );
  AND _278_ (
    .A(_125_),
    .B(_126_),
    .Y(_009_)
  );
  NAND _279_ (
    .A(_065_),
    .B(\pc_i[19] ),
    .Y(_127_)
  );
  NAND _280_ (
    .A(_068_),
    .B(_127_),
    .Y(_128_)
  );
  OR _281_ (
    .A(\pc_o[19] ),
    .B(_068_),
    .Y(_129_)
  );
  AND _282_ (
    .A(_128_),
    .B(_129_),
    .Y(_010_)
  );
  NAND _283_ (
    .A(_065_),
    .B(\pc_i[20] ),
    .Y(_130_)
  );
  NAND _284_ (
    .A(_068_),
    .B(_130_),
    .Y(_131_)
  );
  OR _285_ (
    .A(\pc_o[20] ),
    .B(_068_),
    .Y(_132_)
  );
  AND _286_ (
    .A(_131_),
    .B(_132_),
    .Y(_012_)
  );
  NAND _287_ (
    .A(_065_),
    .B(\pc_i[21] ),
    .Y(_133_)
  );
  NAND _288_ (
    .A(_068_),
    .B(_133_),
    .Y(_134_)
  );
  OR _289_ (
    .A(\pc_o[21] ),
    .B(_068_),
    .Y(_135_)
  );
  AND _290_ (
    .A(_134_),
    .B(_135_),
    .Y(_013_)
  );
  NAND _291_ (
    .A(_065_),
    .B(\pc_i[22] ),
    .Y(_136_)
  );
  NAND _292_ (
    .A(_068_),
    .B(_136_),
    .Y(_137_)
  );
  OR _293_ (
    .A(\pc_o[22] ),
    .B(_068_),
    .Y(_138_)
  );
  AND _294_ (
    .A(_137_),
    .B(_138_),
    .Y(_014_)
  );
  NAND _295_ (
    .A(_065_),
    .B(\pc_i[23] ),
    .Y(_139_)
  );
  NAND _296_ (
    .A(_068_),
    .B(_139_),
    .Y(_140_)
  );
  OR _297_ (
    .A(\pc_o[23] ),
    .B(_068_),
    .Y(_141_)
  );
  AND _298_ (
    .A(_140_),
    .B(_141_),
    .Y(_015_)
  );
  NAND _299_ (
    .A(_065_),
    .B(\pc_i[24] ),
    .Y(_142_)
  );
  NAND _300_ (
    .A(_068_),
    .B(_142_),
    .Y(_143_)
  );
  OR _301_ (
    .A(\pc_o[24] ),
    .B(_068_),
    .Y(_144_)
  );
  AND _302_ (
    .A(_143_),
    .B(_144_),
    .Y(_016_)
  );
  NAND _303_ (
    .A(_065_),
    .B(\pc_i[25] ),
    .Y(_145_)
  );
  NAND _304_ (
    .A(_068_),
    .B(_145_),
    .Y(_146_)
  );
  OR _305_ (
    .A(\pc_o[25] ),
    .B(_068_),
    .Y(_147_)
  );
  AND _306_ (
    .A(_146_),
    .B(_147_),
    .Y(_017_)
  );
  NAND _307_ (
    .A(_065_),
    .B(\pc_i[26] ),
    .Y(_148_)
  );
  NAND _308_ (
    .A(_068_),
    .B(_148_),
    .Y(_149_)
  );
  OR _309_ (
    .A(\pc_o[26] ),
    .B(_068_),
    .Y(_150_)
  );
  AND _310_ (
    .A(_149_),
    .B(_150_),
    .Y(_018_)
  );
  NAND _311_ (
    .A(_065_),
    .B(\pc_i[27] ),
    .Y(_151_)
  );
  NAND _312_ (
    .A(_068_),
    .B(_151_),
    .Y(_152_)
  );
  OR _313_ (
    .A(\pc_o[27] ),
    .B(_068_),
    .Y(_153_)
  );
  AND _314_ (
    .A(_152_),
    .B(_153_),
    .Y(_019_)
  );
  NAND _315_ (
    .A(_065_),
    .B(\pc_i[28] ),
    .Y(_154_)
  );
  NAND _316_ (
    .A(_068_),
    .B(_154_),
    .Y(_155_)
  );
  OR _317_ (
    .A(\pc_o[28] ),
    .B(_068_),
    .Y(_156_)
  );
  AND _318_ (
    .A(_155_),
    .B(_156_),
    .Y(_020_)
  );
  NAND _319_ (
    .A(_065_),
    .B(\pc_i[29] ),
    .Y(_157_)
  );
  NAND _320_ (
    .A(_068_),
    .B(_157_),
    .Y(_158_)
  );
  OR _321_ (
    .A(\pc_o[29] ),
    .B(_068_),
    .Y(_159_)
  );
  AND _322_ (
    .A(_158_),
    .B(_159_),
    .Y(_021_)
  );
  NAND _323_ (
    .A(_065_),
    .B(\pc_i[30] ),
    .Y(_160_)
  );
  NAND _324_ (
    .A(_068_),
    .B(_160_),
    .Y(_161_)
  );
  OR _325_ (
    .A(\pc_o[30] ),
    .B(_068_),
    .Y(_162_)
  );
  AND _326_ (
    .A(_161_),
    .B(_162_),
    .Y(_023_)
  );
  NAND _327_ (
    .A(_065_),
    .B(\pc_i[31] ),
    .Y(_163_)
  );
  NAND _328_ (
    .A(_068_),
    .B(_163_),
    .Y(_164_)
  );
  OR _329_ (
    .A(\pc_o[31] ),
    .B(_068_),
    .Y(_165_)
  );
  AND _330_ (
    .A(_164_),
    .B(_165_),
    .Y(_024_)
  );
  NOR _331_ (
    .A(\pc_i[16] ),
    .B(\pc_i[17] ),
    .Y(_166_)
  );
  NOR _332_ (
    .A(\pc_i[18] ),
    .B(\pc_i[19] ),
    .Y(_167_)
  );
  AND _333_ (
    .A(_166_),
    .B(_167_),
    .Y(_168_)
  );
  NOR _334_ (
    .A(\pc_i[20] ),
    .B(\pc_i[21] ),
    .Y(_169_)
  );
  NOR _335_ (
    .A(\pc_i[22] ),
    .B(\pc_i[23] ),
    .Y(_170_)
  );
  AND _336_ (
    .A(_169_),
    .B(_170_),
    .Y(_171_)
  );
  AND _337_ (
    .A(_168_),
    .B(_171_),
    .Y(_172_)
  );
  NOR _338_ (
    .A(\pc_i[28] ),
    .B(\pc_i[29] ),
    .Y(_173_)
  );
  NOR _339_ (
    .A(\pc_i[30] ),
    .B(\pc_i[31] ),
    .Y(_174_)
  );
  AND _340_ (
    .A(_173_),
    .B(_174_),
    .Y(_175_)
  );
  NOR _341_ (
    .A(\pc_i[24] ),
    .B(\pc_i[25] ),
    .Y(_176_)
  );
  NOR _342_ (
    .A(\pc_i[26] ),
    .B(\pc_i[27] ),
    .Y(_177_)
  );
  AND _343_ (
    .A(_176_),
    .B(_177_),
    .Y(_178_)
  );
  AND _344_ (
    .A(_175_),
    .B(_178_),
    .Y(_179_)
  );
  AND _345_ (
    .A(_172_),
    .B(_179_),
    .Y(_180_)
  );
  AND _346_ (
    .A(\pc_i[4] ),
    .B(\pc_i[5] ),
    .Y(_181_)
  );
  AND _347_ (
    .A(\pc_i[6] ),
    .B(\pc_i[7] ),
    .Y(_182_)
  );
  AND _348_ (
    .A(_181_),
    .B(_182_),
    .Y(_183_)
  );
  NOR _349_ (
    .A(\pc_i[0] ),
    .B(\pc_i[1] ),
    .Y(_184_)
  );
  AND _350_ (
    .A(_066_),
    .B(\pc_i[3] ),
    .Y(_185_)
  );
  AND _351_ (
    .A(_184_),
    .B(_185_),
    .Y(_186_)
  );
  AND _352_ (
    .A(_183_),
    .B(_186_),
    .Y(_187_)
  );
  NOR _353_ (
    .A(\pc_i[8] ),
    .B(\pc_i[9] ),
    .Y(_188_)
  );
  NOR _354_ (
    .A(\pc_i[10] ),
    .B(\pc_i[11] ),
    .Y(_189_)
  );
  AND _355_ (
    .A(_188_),
    .B(_189_),
    .Y(_190_)
  );
  NOR _356_ (
    .A(\pc_i[12] ),
    .B(\pc_i[13] ),
    .Y(_191_)
  );
  NOR _357_ (
    .A(\pc_i[14] ),
    .B(\pc_i[15] ),
    .Y(_192_)
  );
  AND _358_ (
    .A(_191_),
    .B(_192_),
    .Y(_193_)
  );
  AND _359_ (
    .A(_190_),
    .B(_193_),
    .Y(_194_)
  );
  AND _360_ (
    .A(_187_),
    .B(_194_),
    .Y(_195_)
  );
  NAND _361_ (
    .A(_180_),
    .B(_195_),
    .Y(_196_)
  );
  NAND _362_ (
    .A(_065_),
    .B(_196_),
    .Y(flag_next)
  );
  NOT _363_ (
    .A(start_i),
    .Y(_032_)
  );
  NOT _364_ (
    .A(start_i),
    .Y(_033_)
  );
  NOT _365_ (
    .A(start_i),
    .Y(_034_)
  );
  NOT _366_ (
    .A(start_i),
    .Y(_035_)
  );
  NOT _367_ (
    .A(start_i),
    .Y(_036_)
  );
  NOT _368_ (
    .A(start_i),
    .Y(_037_)
  );
  NOT _369_ (
    .A(start_i),
    .Y(_038_)
  );
  NOT _370_ (
    .A(start_i),
    .Y(_039_)
  );
  NOT _371_ (
    .A(start_i),
    .Y(_040_)
  );
  NOT _372_ (
    .A(start_i),
    .Y(_041_)
  );
  NOT _373_ (
    .A(start_i),
    .Y(_042_)
  );
  NOT _374_ (
    .A(start_i),
    .Y(_043_)
  );
  NOT _375_ (
    .A(start_i),
    .Y(_044_)
  );
  NOT _376_ (
    .A(start_i),
    .Y(_045_)
  );
  NOT _377_ (
    .A(start_i),
    .Y(_046_)
  );
  NOT _378_ (
    .A(start_i),
    .Y(_047_)
  );
  NOT _379_ (
    .A(start_i),
    .Y(_048_)
  );
  NOT _380_ (
    .A(start_i),
    .Y(_049_)
  );
  NOT _381_ (
    .A(start_i),
    .Y(_050_)
  );
  NOT _382_ (
    .A(start_i),
    .Y(_051_)
  );
  NOT _383_ (
    .A(start_i),
    .Y(_052_)
  );
  NOT _384_ (
    .A(start_i),
    .Y(_053_)
  );
  NOT _385_ (
    .A(start_i),
    .Y(_054_)
  );
  NOT _386_ (
    .A(start_i),
    .Y(_055_)
  );
  NOT _387_ (
    .A(start_i),
    .Y(_056_)
  );
  NOT _388_ (
    .A(start_i),
    .Y(_057_)
  );
  NOT _389_ (
    .A(start_i),
    .Y(_058_)
  );
  NOT _390_ (
    .A(start_i),
    .Y(_059_)
  );
  NOT _391_ (
    .A(start_i),
    .Y(_060_)
  );
  NOT _392_ (
    .A(start_i),
    .Y(_061_)
  );
  NOT _393_ (
    .A(start_i),
    .Y(_062_)
  );
  NOT _394_ (
    .A(start_i),
    .Y(_063_)
  );
  (* src = "PC.v:46" *)
  DFFSR _395_ (
    .C(clk_i),
    .D(_000_),
    .SE(se),
    .SI(si),
    .Q(\pc_o[0]),
    .R(_032_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _396_ (
    .C(clk_i),
    .D(_011_),
    .SE(se),
    .SI(\pc_o[0]),
    .Q(\pc_o[1] ),
    .R(_033_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _397_ (
    .C(clk_i),
    .D(_022_),
    .SE(se),
    .SI(\pc_o[1]),
    .Q(\pc_o[2] ),
    .R(_034_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _398_ (
    .C(clk_i),
    .D(_025_),
    .SE(se),
    .SI(\pc_o[2]),
    .Q(\pc_o[3] ),
    .R(_035_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _399_ (
    .C(clk_i),
    .D(_026_),
    .SE(se),
    .SI(\pc_o[3]),
    .Q(\pc_o[4] ),
    .R(_036_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _400_ (
    .C(clk_i),
    .D(_027_),
    .SE(se),
    .SI(\pc_o[4]),
    .Q(\pc_o[5] ),
    .R(_037_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _401_ (
    .C(clk_i),
    .D(_028_),
    .SE(se),
    .SI(\pc_o[5]),
    .Q(\pc_o[6] ),
    .R(_038_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _402_ (
    .C(clk_i),
    .D(_029_),
    .SE(se),
    .SI(\pc_o[6]),
    .Q(\pc_o[7] ),
    .R(_039_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _403_ (
    .C(clk_i),
    .D(_030_),
    .SE(se),
    .SI(\pc_o[7]),
    .Q(\pc_o[8] ),
    .R(_040_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _404_ (
    .C(clk_i),
    .D(_031_),
    .SE(se),
    .SI(\pc_o[8]),
    .Q(\pc_o[9] ),
    .R(_041_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _405_ (
    .C(clk_i),
    .D(_001_),
    .SE(se),
    .SI(\pc_o[9]),
    .Q(\pc_o[10] ),
    .R(_042_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _406_ (
    .C(clk_i),
    .D(_002_),
    .SE(se),
    .SI(\pc_o[10]),
    .Q(\pc_o[11] ),
    .R(_043_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _407_ (
    .C(clk_i),
    .D(_003_),
    .SE(se),
    .SI(\pc_o[11]),
    .Q(\pc_o[12] ),
    .R(_044_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _408_ (
    .C(clk_i),
    .D(_004_),
    .SE(se),
    .SI(\pc_o[12]),
    .Q(\pc_o[13] ),
    .R(_045_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _409_ (
    .C(clk_i),
    .D(_005_),
    .SE(se),
    .SI(\pc_o[13]),
    .Q(\pc_o[14] ),
    .R(_046_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _410_ (
    .C(clk_i),
    .D(_006_),
    .SE(se),
    .SI(\pc_o[14]),
    .Q(\pc_o[15] ),
    .R(_047_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _411_ (
    .C(clk_i),
    .D(_007_),
    .SE(se),
    .SI(\pc_o[15]),
    .Q(\pc_o[16] ),
    .R(_048_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _412_ (
    .C(clk_i),
    .D(_008_),
    .SE(se),
    .SI(\pc_o[16]),
    .Q(\pc_o[17] ),
    .R(_049_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _413_ (
    .C(clk_i),
    .D(_009_),
    .SE(se),
    .SI(\pc_o[17]),
    .Q(\pc_o[18] ),
    .R(_050_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _414_ (
    .C(clk_i),
    .D(_010_),
    .SE(se),
    .SI(\pc_o[18]),
    .Q(\pc_o[19] ),
    .R(_051_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _415_ (
    .C(clk_i),
    .D(_012_),
    .SE(se),
    .SI(\pc_o[19]),
    .Q(\pc_o[20] ),
    .R(_052_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _416_ (
    .C(clk_i),
    .D(_013_),
    .SE(se),
    .SI(\pc_o[20]),
    .Q(\pc_o[21] ),
    .R(_053_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _417_ (
    .C(clk_i),
    .D(_014_),
    .SE(se),
    .SI(\pc_o[21]),
    .Q(\pc_o[22] ),
    .R(_054_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _418_ (
    .C(clk_i),
    .D(_015_),
    .SE(se),
    .SI(\pc_o[22]),
    .Q(\pc_o[23] ),
    .R(_055_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _419_ (
    .C(clk_i),
    .D(_016_),
    .SE(se),
    .SI(\pc_o[23]),
    .Q(\pc_o[24] ),
    .R(_056_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _420_ (
    .C(clk_i),
    .D(_017_),
    .SE(se),
    .SI(\pc_o[24]),
    .Q(\pc_o[25] ),
    .R(_057_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _421_ (
    .C(clk_i),
    .D(_018_),
    .SE(se),
    .SI(\pc_o[25]),
    .Q(\pc_o[26] ),
    .R(_058_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _422_ (
    .C(clk_i),
    .D(_019_),
    .SE(se),
    .SI(\pc_o[26]),
    .Q(\pc_o[27] ),
    .R(_059_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _423_ (
    .C(clk_i),
    .D(_020_),
    .SE(se),
    .SI(\pc_o[27]),
    .Q(\pc_o[28] ),
    .R(_060_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _424_ (
    .C(clk_i),
    .D(_021_),
    .SE(se),
    .SI(\pc_o[28]),
    .Q(\pc_o[29] ),
    .R(_061_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _425_ (
    .C(clk_i),
    .D(_023_),
    .SE(se),
    .SI(\pc_o[29]),
    .Q(\pc_o[30] ),
    .R(_062_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _426_ (
    .C(clk_i),
    .D(_024_),
    .SE(se),
    .SI(\pc_o[30]),
    .Q(\pc_o[31] ),
    .R(_063_),
    .S(1'h0)
  );
  (* src = "PC.v:46" *)
  DFFSR _427_ (
    .C(clk_i),
    .D(flag_next),
    .SE(se),
    .SI(\pc_o[31]),
    .Q(flag),
    .R(_064_),
    .S(1'h0)
  );
endmodule
