/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "Shift2.v:23" *)
module Shift2(\data_i[0] , \data_i[1] , \data_i[2] , \data_i[3] , \data_i[4] , \data_i[5] , \data_i[6] , \data_i[7] , \data_i[8] , \data_i[9] , \data_i[10] , \data_i[11] , \data_i[12] , \data_i[13] , \data_i[14] , \data_i[15] , \data_i[16] , \data_i[17] , \data_i[18] , \data_i[19] , \data_i[20] , \data_i[21] , \data_i[22] , \data_i[23] , \data_i[24] , \data_i[25] , \data_i[26] , \data_i[27] , \data_i[28] , \data_i[29] , \data_i[30] , \data_i[31] , \data_o[0] , \data_o[1] , \data_o[2] , \data_o[3] , \data_o[4] , \data_o[5] , \data_o[6] , \data_o[7] , \data_o[8] , \data_o[9] , \data_o[10] , \data_o[11] , \data_o[12] , \data_o[13] , \data_o[14] , \data_o[15] , \data_o[16] , \data_o[17] , \data_o[18] , \data_o[19] , \data_o[20] , \data_o[21] , \data_o[22] , \data_o[23] , \data_o[24] , \data_o[25] , \data_o[26] , \data_o[27] , \data_o[28] , \data_o[29] , \data_o[30] , \data_o[31] );
  (* src = "Shift2.v:24" *)
  input \data_i[0] ;
  (* src = "Shift2.v:24" *)
  input \data_i[10] ;
  (* src = "Shift2.v:24" *)
  input \data_i[11] ;
  (* src = "Shift2.v:24" *)
  input \data_i[12] ;
  (* src = "Shift2.v:24" *)
  input \data_i[13] ;
  (* src = "Shift2.v:24" *)
  input \data_i[14] ;
  (* src = "Shift2.v:24" *)
  input \data_i[15] ;
  (* src = "Shift2.v:24" *)
  input \data_i[16] ;
  (* src = "Shift2.v:24" *)
  input \data_i[17] ;
  (* src = "Shift2.v:24" *)
  input \data_i[18] ;
  (* src = "Shift2.v:24" *)
  input \data_i[19] ;
  (* src = "Shift2.v:24" *)
  input \data_i[1] ;
  (* src = "Shift2.v:24" *)
  input \data_i[20] ;
  (* src = "Shift2.v:24" *)
  input \data_i[21] ;
  (* src = "Shift2.v:24" *)
  input \data_i[22] ;
  (* src = "Shift2.v:24" *)
  input \data_i[23] ;
  (* src = "Shift2.v:24" *)
  input \data_i[24] ;
  (* src = "Shift2.v:24" *)
  input \data_i[25] ;
  (* src = "Shift2.v:24" *)
  input \data_i[26] ;
  (* src = "Shift2.v:24" *)
  input \data_i[27] ;
  (* src = "Shift2.v:24" *)
  input \data_i[28] ;
  (* src = "Shift2.v:24" *)
  input \data_i[29] ;
  (* src = "Shift2.v:24" *)
  input \data_i[2] ;
  (* src = "Shift2.v:24" *)
  input \data_i[30] ;
  (* src = "Shift2.v:24" *)
  input \data_i[31] ;
  (* src = "Shift2.v:24" *)
  input \data_i[3] ;
  (* src = "Shift2.v:24" *)
  input \data_i[4] ;
  (* src = "Shift2.v:24" *)
  input \data_i[5] ;
  (* src = "Shift2.v:24" *)
  input \data_i[6] ;
  (* src = "Shift2.v:24" *)
  input \data_i[7] ;
  (* src = "Shift2.v:24" *)
  input \data_i[8] ;
  (* src = "Shift2.v:24" *)
  input \data_i[9] ;
  (* src = "Shift2.v:25" *)
  output \data_o[0] ;
  (* src = "Shift2.v:25" *)
  output \data_o[10] ;
  (* src = "Shift2.v:25" *)
  output \data_o[11] ;
  (* src = "Shift2.v:25" *)
  output \data_o[12] ;
  (* src = "Shift2.v:25" *)
  output \data_o[13] ;
  (* src = "Shift2.v:25" *)
  output \data_o[14] ;
  (* src = "Shift2.v:25" *)
  output \data_o[15] ;
  (* src = "Shift2.v:25" *)
  output \data_o[16] ;
  (* src = "Shift2.v:25" *)
  output \data_o[17] ;
  (* src = "Shift2.v:25" *)
  output \data_o[18] ;
  (* src = "Shift2.v:25" *)
  output \data_o[19] ;
  (* src = "Shift2.v:25" *)
  output \data_o[1] ;
  (* src = "Shift2.v:25" *)
  output \data_o[20] ;
  (* src = "Shift2.v:25" *)
  output \data_o[21] ;
  (* src = "Shift2.v:25" *)
  output \data_o[22] ;
  (* src = "Shift2.v:25" *)
  output \data_o[23] ;
  (* src = "Shift2.v:25" *)
  output \data_o[24] ;
  (* src = "Shift2.v:25" *)
  output \data_o[25] ;
  (* src = "Shift2.v:25" *)
  output \data_o[26] ;
  (* src = "Shift2.v:25" *)
  output \data_o[27] ;
  (* src = "Shift2.v:25" *)
  output \data_o[28] ;
  (* src = "Shift2.v:25" *)
  output \data_o[29] ;
  (* src = "Shift2.v:25" *)
  output \data_o[2] ;
  (* src = "Shift2.v:25" *)
  output \data_o[30] ;
  (* src = "Shift2.v:25" *)
  output \data_o[31] ;
  (* src = "Shift2.v:25" *)
  output \data_o[3] ;
  (* src = "Shift2.v:25" *)
  output \data_o[4] ;
  (* src = "Shift2.v:25" *)
  output \data_o[5] ;
  (* src = "Shift2.v:25" *)
  output \data_o[6] ;
  (* src = "Shift2.v:25" *)
  output \data_o[7] ;
  (* src = "Shift2.v:25" *)
  output \data_o[8] ;
  (* src = "Shift2.v:25" *)
  output \data_o[9] ;
  assign \data_o[0]  = 1'h0;
  assign \data_o[10]  = \data_i[9] ;
  assign \data_o[11]  = \data_i[10] ;
  assign \data_o[12]  = \data_i[11] ;
  assign \data_o[13]  = \data_i[12] ;
  assign \data_o[14]  = \data_i[13] ;
  assign \data_o[15]  = \data_i[14] ;
  assign \data_o[16]  = \data_i[15] ;
  assign \data_o[17]  = \data_i[16] ;
  assign \data_o[18]  = \data_i[17] ;
  assign \data_o[19]  = \data_i[18] ;
  assign \data_o[1]  = \data_i[0] ;
  assign \data_o[20]  = \data_i[19] ;
  assign \data_o[21]  = \data_i[20] ;
  assign \data_o[22]  = \data_i[21] ;
  assign \data_o[23]  = \data_i[22] ;
  assign \data_o[24]  = \data_i[23] ;
  assign \data_o[25]  = \data_i[24] ;
  assign \data_o[26]  = \data_i[25] ;
  assign \data_o[27]  = \data_i[26] ;
  assign \data_o[28]  = \data_i[27] ;
  assign \data_o[29]  = \data_i[28] ;
  assign \data_o[2]  = \data_i[1] ;
  assign \data_o[30]  = \data_i[29] ;
  assign \data_o[31]  = \data_i[30] ;
  assign \data_o[3]  = \data_i[2] ;
  assign \data_o[4]  = \data_i[3] ;
  assign \data_o[5]  = \data_i[4] ;
  assign \data_o[6]  = \data_i[5] ;
  assign \data_o[7]  = \data_i[6] ;
  assign \data_o[8]  = \data_i[7] ;
  assign \data_o[9]  = \data_i[8] ;
endmodule
