/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "Sign_Extender.v:23" *)
module Sign_Extender(select_i, \data0_i[0] , \data0_i[1] , \data0_i[2] , \data0_i[3] , \data0_i[4] , \data0_i[5] , \data0_i[6] , \data0_i[7] , \data0_i[8] , \data0_i[9] , \data0_i[10] , \data0_i[11] , \data1_i[0] , \data1_i[1] , \data1_i[2] , \data1_i[3] , \data1_i[4] , \data1_i[5] , \data1_i[6] , \data1_i[7] , \data1_i[8] , \data1_i[9] , \data1_i[10] , \data1_i[11] , \data_o[0] , \data_o[1] , \data_o[2] , \data_o[3] , \data_o[4] , \data_o[5] , \data_o[6] , \data_o[7] , \data_o[8] , \data_o[9] , \data_o[10] , \data_o[11] , \data_o[12] , \data_o[13] , \data_o[14] , \data_o[15] , \data_o[16] , \data_o[17] , \data_o[18] , \data_o[19] , \data_o[20] , \data_o[21] , \data_o[22] , \data_o[23] , \data_o[24] , \data_o[25] , \data_o[26] , \data_o[27] , \data_o[28] , \data_o[29] , \data_o[30] , \data_o[31] );
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  (* src = "Sign_Extender.v:29" *)
  input \data0_i[0] ;
  (* src = "Sign_Extender.v:29" *)
  input \data0_i[10] ;
  (* src = "Sign_Extender.v:29" *)
  input \data0_i[11] ;
  (* src = "Sign_Extender.v:29" *)
  input \data0_i[1] ;
  (* src = "Sign_Extender.v:29" *)
  input \data0_i[2] ;
  (* src = "Sign_Extender.v:29" *)
  input \data0_i[3] ;
  (* src = "Sign_Extender.v:29" *)
  input \data0_i[4] ;
  (* src = "Sign_Extender.v:29" *)
  input \data0_i[5] ;
  (* src = "Sign_Extender.v:29" *)
  input \data0_i[6] ;
  (* src = "Sign_Extender.v:29" *)
  input \data0_i[7] ;
  (* src = "Sign_Extender.v:29" *)
  input \data0_i[8] ;
  (* src = "Sign_Extender.v:29" *)
  input \data0_i[9] ;
  (* src = "Sign_Extender.v:29" *)
  input \data1_i[0] ;
  (* src = "Sign_Extender.v:29" *)
  input \data1_i[10] ;
  (* src = "Sign_Extender.v:29" *)
  input \data1_i[11] ;
  (* src = "Sign_Extender.v:29" *)
  input \data1_i[1] ;
  (* src = "Sign_Extender.v:29" *)
  input \data1_i[2] ;
  (* src = "Sign_Extender.v:29" *)
  input \data1_i[3] ;
  (* src = "Sign_Extender.v:29" *)
  input \data1_i[4] ;
  (* src = "Sign_Extender.v:29" *)
  input \data1_i[5] ;
  (* src = "Sign_Extender.v:29" *)
  input \data1_i[6] ;
  (* src = "Sign_Extender.v:29" *)
  input \data1_i[7] ;
  (* src = "Sign_Extender.v:29" *)
  input \data1_i[8] ;
  (* src = "Sign_Extender.v:29" *)
  input \data1_i[9] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[0] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[10] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[11] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[12] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[13] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[14] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[15] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[16] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[17] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[18] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[19] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[1] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[20] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[21] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[22] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[23] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[24] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[25] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[26] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[27] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[28] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[29] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[2] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[30] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[31] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[3] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[4] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[5] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[6] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[7] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[8] ;
  (* src = "Sign_Extender.v:31" *)
  output \data_o[9] ;
  (* src = "Sign_Extender.v:30" *)
  input select_i;
  NAND _25_ (
    .A(select_i),
    .B(\data1_i[9] ),
    .Y(_19_)
  );
  NAND _26_ (
    .A(_00_),
    .B(\data0_i[9] ),
    .Y(_20_)
  );
  NAND _27_ (
    .A(_19_),
    .B(_20_),
    .Y(\data_o[9] )
  );
  NAND _28_ (
    .A(select_i),
    .B(\data1_i[10] ),
    .Y(_21_)
  );
  NAND _29_ (
    .A(_00_),
    .B(\data0_i[10] ),
    .Y(_22_)
  );
  NAND _30_ (
    .A(_21_),
    .B(_22_),
    .Y(\data_o[10] )
  );
  NAND _31_ (
    .A(select_i),
    .B(\data1_i[11] ),
    .Y(_23_)
  );
  NAND _32_ (
    .A(_00_),
    .B(\data0_i[11] ),
    .Y(_24_)
  );
  NAND _33_ (
    .A(_23_),
    .B(_24_),
    .Y(\data_o[11] )
  );
  NOT _34_ (
    .A(select_i),
    .Y(_00_)
  );
  NAND _35_ (
    .A(\data1_i[0] ),
    .B(select_i),
    .Y(_01_)
  );
  NAND _36_ (
    .A(\data0_i[0] ),
    .B(_00_),
    .Y(_02_)
  );
  NAND _37_ (
    .A(_01_),
    .B(_02_),
    .Y(\data_o[0] )
  );
  NAND _38_ (
    .A(select_i),
    .B(\data1_i[1] ),
    .Y(_03_)
  );
  NAND _39_ (
    .A(_00_),
    .B(\data0_i[1] ),
    .Y(_04_)
  );
  NAND _40_ (
    .A(_03_),
    .B(_04_),
    .Y(\data_o[1] )
  );
  NAND _41_ (
    .A(select_i),
    .B(\data1_i[2] ),
    .Y(_05_)
  );
  NAND _42_ (
    .A(_00_),
    .B(\data0_i[2] ),
    .Y(_06_)
  );
  NAND _43_ (
    .A(_05_),
    .B(_06_),
    .Y(\data_o[2] )
  );
  NAND _44_ (
    .A(select_i),
    .B(\data1_i[3] ),
    .Y(_07_)
  );
  NAND _45_ (
    .A(_00_),
    .B(\data0_i[3] ),
    .Y(_08_)
  );
  NAND _46_ (
    .A(_07_),
    .B(_08_),
    .Y(\data_o[3] )
  );
  NAND _47_ (
    .A(select_i),
    .B(\data1_i[4] ),
    .Y(_09_)
  );
  NAND _48_ (
    .A(_00_),
    .B(\data0_i[4] ),
    .Y(_10_)
  );
  NAND _49_ (
    .A(_09_),
    .B(_10_),
    .Y(\data_o[4] )
  );
  NAND _50_ (
    .A(select_i),
    .B(\data1_i[5] ),
    .Y(_11_)
  );
  NAND _51_ (
    .A(_00_),
    .B(\data0_i[5] ),
    .Y(_12_)
  );
  NAND _52_ (
    .A(_11_),
    .B(_12_),
    .Y(\data_o[5] )
  );
  NAND _53_ (
    .A(select_i),
    .B(\data1_i[6] ),
    .Y(_13_)
  );
  NAND _54_ (
    .A(_00_),
    .B(\data0_i[6] ),
    .Y(_14_)
  );
  NAND _55_ (
    .A(_13_),
    .B(_14_),
    .Y(\data_o[6] )
  );
  NAND _56_ (
    .A(select_i),
    .B(\data1_i[7] ),
    .Y(_15_)
  );
  NAND _57_ (
    .A(_00_),
    .B(\data0_i[7] ),
    .Y(_16_)
  );
  NAND _58_ (
    .A(_15_),
    .B(_16_),
    .Y(\data_o[7] )
  );
  NAND _59_ (
    .A(select_i),
    .B(\data1_i[8] ),
    .Y(_17_)
  );
  NAND _60_ (
    .A(_00_),
    .B(\data0_i[8] ),
    .Y(_18_)
  );
  NAND _61_ (
    .A(_17_),
    .B(_18_),
    .Y(\data_o[8] )
  );
  assign \data_o[12]  = \data_o[11] ;
  assign \data_o[13]  = \data_o[11] ;
  assign \data_o[14]  = \data_o[11] ;
  assign \data_o[15]  = \data_o[11] ;
  assign \data_o[16]  = \data_o[11] ;
  assign \data_o[17]  = \data_o[11] ;
  assign \data_o[18]  = \data_o[11] ;
  assign \data_o[19]  = \data_o[11] ;
  assign \data_o[20]  = \data_o[11] ;
  assign \data_o[21]  = \data_o[11] ;
  assign \data_o[22]  = \data_o[11] ;
  assign \data_o[23]  = \data_o[11] ;
  assign \data_o[24]  = \data_o[11] ;
  assign \data_o[25]  = \data_o[11] ;
  assign \data_o[26]  = \data_o[11] ;
  assign \data_o[27]  = \data_o[11] ;
  assign \data_o[28]  = \data_o[11] ;
  assign \data_o[29]  = \data_o[11] ;
  assign \data_o[30]  = \data_o[11] ;
  assign \data_o[31]  = \data_o[11] ;
endmodule
